
# Site settings

locale                   : "en-US"
title                    : "John Doe's Blog"
title_separator          : "-"
name                     : "John Doe"
description              : "Portfolio and blog"
url                      : https://nvnmo.github.io
baseurl                  :
paginate                 : 5
paginate_path            : "blog/:num/"
date_format              : "%b %-d, %Y"
author: 
  name                   : "John Doe"
  avatar                 : https://api.adorable.io/avatars/209/abott@adorable.png
  bio                    : "Awesome person long bio"




plugins:
  - jekyll-paginate
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock


# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

# Header nav
header_pages:
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Portfolio
    url: /portfolio


# Collection
collections:
  projects:
    output: true
    permalink: /portfolio/:title/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: blog-post
      basetype: blog
      permalink: /blog/:year/:month/:day/:title
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      basetype: blog

    # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: portfolio
      basetype: blog